name: provenance_dart
version: 2.0.1
description: A native flutter library for interacting with the provenance wallet.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ecdsa: 0.0.4
  grpc: 3.2.4
  json_annotation: ^4.8.1
  protobuf: 3.1.0
  secp256k1: 0.3.0
  sha3: 0.2.0
  web_socket_channel: ^2.4.0
  encrypt: ^5.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 2.3.3
  json_serializable: ^6.6.2
  mockito: ^5.0.17
